server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/JWT
    username: postgres
    password: 1273
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

  application:
    name: tracinglogs
